import React from 'react'
import Footer from './Footer.jsx';
import Header from './Header.js';
import Head from 'next/head'

const Layout = ({children,title}) => {
  return (
    <div>
    <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous"></link>
    </Head>
    <Header/>
    {children}
    <Footer/>
    </div>
  )
}

export default Layout